import Foundation
import GRDB

struct Folder: Codable, Identifiable {
    var id: UUID
    var name: String
    var isAutoGenerated: Bool
    var createdAt: Date

    init(
        id: UUID = UUID(),
        name: String,
        isAutoGenerated: Bool = false,
        createdAt: Date = Date()
    ) {
        self.id = id
        self.name = name
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = createdAt
    }
}

// MARK: - GRDB Conformance

extension Folder: FetchableRecord, PersistableRecord {
    static let databaseTableName = "folders"

    enum Columns {
        static let id = Column(CodingKeys.id)
        static let name = Column(CodingKeys.name)
        static let isAutoGenerated = Column(CodingKeys.isAutoGenerated)
        static let createdAt = Column(CodingKeys.createdAt)
    }
}

// MARK: - Relationships

extension Folder {
    static let videos = hasMany(Video.self)
    var videos: QueryInterfaceRequest<Video> {
        request(for: Folder.videos)
    }
}

// MARK: - Factory Methods

extension Folder {
    /// Creates an auto-generated folder for a source domain
    static func autoFolder(for domain: String) -> Folder {
        Folder(
            name: domain,
            isAutoGenerated: true
        )
    }
}
