import Foundation
import GRDB

final class DatabaseManager {
    static let shared = DatabaseManager()

    private var dbPool: DatabasePool?

    var databasePool: DatabasePool {
        guard let pool = dbPool else {
            fatalError("Database not initialized. Call initialize() first.")
        }
        return pool
    }

    private init() {}

    func initialize() {
        do {
            let fileManager = FileManager.default
            let documentsURL = try fileManager.url(
                for: .documentDirectory,
                in: .userDomainMask,
                appropriateFor: nil,
                create: true
            )
            let databaseURL = documentsURL.appendingPathComponent("offlinebrowser.sqlite")

            var config = Configuration()
            #if DEBUG
            config.prepareDatabase { db in
                db.trace { print("SQL: \($0)") }
            }
            #endif

            dbPool = try DatabasePool(path: databaseURL.path, configuration: config)

            try migrator.migrate(databasePool)

            print("Database initialized at: \(databaseURL.path)")
        } catch {
            fatalError("Failed to initialize database: \(error)")
        }
    }

    private var migrator: DatabaseMigrator {
        var migrator = DatabaseMigrator()

        // NOTE: Do NOT enable eraseDatabaseOnSchemaChange even in DEBUG
        // as it will delete all user data when schema changes
        // migrator.eraseDatabaseOnSchemaChange = true

        // Migration 1: Initial schema
        migrator.registerMigration("v1_initial") { db in
            // Folders table
            try db.create(table: "folders") { t in
                t.column("id", .text).primaryKey()
                t.column("name", .text).notNull()
                t.column("isAutoGenerated", .boolean).notNull().defaults(to: false)
                t.column("createdAt", .datetime).notNull()
            }

            // Videos table
            try db.create(table: "videos") { t in
                t.column("id", .text).primaryKey()
                t.column("title", .text).notNull()
                t.column("sourceURL", .text).notNull()
                t.column("sourceDomain", .text).notNull()
                t.column("filePath", .text).notNull()
                t.column("thumbnailPath", .text)
                t.column("subtitlePath", .text)
                t.column("duration", .integer).notNull().defaults(to: 0)
                t.column("fileSize", .integer).notNull().defaults(to: 0)
                t.column("quality", .text).notNull()
                t.column("folderID", .text).references("folders", onDelete: .setNull)
                t.column("createdAt", .datetime).notNull()
                t.column("lastPlayedAt", .datetime)
                t.column("playbackPosition", .integer).notNull().defaults(to: 0)
            }

            // Downloads table
            try db.create(table: "downloads") { t in
                t.column("id", .text).primaryKey()
                t.column("videoURL", .text).notNull()
                t.column("manifestURL", .text)
                t.column("pageTitle", .text)
                t.column("pageURL", .text)
                t.column("sourceDomain", .text)
                t.column("status", .text).notNull()
                t.column("progress", .double).notNull().defaults(to: 0)
                t.column("segmentsDownloaded", .integer).notNull().defaults(to: 0)
                t.column("segmentsTotal", .integer).notNull().defaults(to: 0)
                t.column("retryCount", .integer).notNull().defaults(to: 0)
                t.column("errorMessage", .text)
                t.column("quality", .text)
                t.column("encryptionKeyURL", .text)
                t.column("createdAt", .datetime).notNull()
                t.column("updatedAt", .datetime).notNull()
            }

            // Preferences table
            try db.create(table: "preferences") { t in
                t.column("key", .text).primaryKey()
                t.column("value", .text).notNull()
            }

            // Indexes
            try db.create(index: "videos_folderID", on: "videos", columns: ["folderID"])
            try db.create(index: "videos_sourceDomain", on: "videos", columns: ["sourceDomain"])
            try db.create(index: "downloads_status", on: "downloads", columns: ["status"])
        }

        // Migration 2: Add thumbnailURL to downloads for og:image support
        migrator.registerMigration("v2_thumbnailURL") { db in
            try db.alter(table: "downloads") { t in
                t.add(column: "thumbnailURL", .text)
            }
        }

        return migrator
    }
}
