import Foundation
@testable import OfflineBrowser

/// Factory methods for creating test data
enum TestFixtures {

    // MARK: - StreamQuality Factories

    static func makeStreamQuality(
        id: UUID = UUID(),
        resolution: String = "1080p",
        bandwidth: Int = 5_000_000,
        url: String = "https://example.com/stream.m3u8",
        codecs: String? = "avc1.64001f,mp4a.40.2"
    ) -> StreamQuality {
        StreamQuality(
            id: id,
            resolution: resolution,
            bandwidth: bandwidth,
            url: url,
            codecs: codecs
        )
    }

    static func makeQualities() -> [StreamQuality] {
        [
            makeStreamQuality(resolution: "1080p", bandwidth: 5_000_000, url: "https://example.com/1080.m3u8"),
            makeStreamQuality(resolution: "720p", bandwidth: 2_500_000, url: "https://example.com/720.m3u8"),
            makeStreamQuality(resolution: "480p", bandwidth: 1_000_000, url: "https://example.com/480.m3u8"),
            makeStreamQuality(resolution: "360p", bandwidth: 500_000, url: "https://example.com/360.m3u8")
        ]
    }

    // MARK: - Video Factories

    static func makeVideo(
        id: UUID = UUID(),
        title: String = "Test Video",
        sourceURL: String = "https://example.com/video",
        sourceDomain: String = "example.com",
        filePath: String = "videos/test/video.mp4",
        thumbnailPath: String? = "videos/test/thumbnail.jpg",
        subtitlePath: String? = nil,
        duration: Int = 3661, // 1:01:01
        fileSize: Int64 = 1_500_000_000, // 1.5 GB
        quality: String = "1080p",
        folderID: UUID? = nil,
        createdAt: Date = Date(),
        lastPlayedAt: Date? = nil,
        playbackPosition: Int = 0
    ) -> Video {
        Video(
            id: id,
            title: title,
            sourceURL: sourceURL,
            sourceDomain: sourceDomain,
            filePath: filePath,
            thumbnailPath: thumbnailPath,
            subtitlePath: subtitlePath,
            duration: duration,
            fileSize: fileSize,
            quality: quality,
            folderID: folderID,
            createdAt: createdAt,
            lastPlayedAt: lastPlayedAt,
            playbackPosition: playbackPosition
        )
    }

    // MARK: - Download Factories

    static func makeDownload(
        id: UUID = UUID(),
        videoURL: String = "https://example.com/video.m3u8",
        manifestURL: String? = "https://example.com/manifest.m3u8",
        pageTitle: String? = "Test Page",
        pageURL: String? = "https://example.com/page",
        sourceDomain: String? = "example.com",
        status: DownloadStatus = .pending,
        progress: Double = 0.0,
        segmentsDownloaded: Int = 0,
        segmentsTotal: Int = 100,
        retryCount: Int = 0,
        errorMessage: String? = nil,
        quality: String? = "1080p",
        encryptionKeyURL: String? = nil,
        createdAt: Date = Date(),
        updatedAt: Date = Date()
    ) -> Download {
        Download(
            id: id,
            videoURL: videoURL,
            manifestURL: manifestURL,
            pageTitle: pageTitle,
            pageURL: pageURL,
            sourceDomain: sourceDomain,
            status: status,
            progress: progress,
            segmentsDownloaded: segmentsDownloaded,
            segmentsTotal: segmentsTotal,
            retryCount: retryCount,
            errorMessage: errorMessage,
            quality: quality,
            encryptionKeyURL: encryptionKeyURL,
            createdAt: createdAt,
            updatedAt: updatedAt
        )
    }

    // MARK: - Folder Factories

    static func makeFolder(
        id: UUID = UUID(),
        name: String = "Test Folder",
        isAutoGenerated: Bool = false,
        createdAt: Date = Date()
    ) -> Folder {
        Folder(
            id: id,
            name: name,
            isAutoGenerated: isAutoGenerated,
            createdAt: createdAt
        )
    }
}
