import XCTest
import GRDB
@testable import OfflineBrowser

final class FolderRepositoryTests: XCTestCase {

    var dbPool: DatabasePool!
    var sut: FolderRepository!

    override func setUp() {
        super.setUp()
        dbPool = try! TestDatabaseManager.makeInMemoryDatabasePool()
        sut = FolderRepository(dbPool: dbPool)
    }

    override func tearDown() {
        sut = nil
        dbPool = nil
        super.tearDown()
    }

    // MARK: - Save Tests

    func testSave_insertsFolderIntoDatabase() throws {
        let folder = TestFixtures.makeFolder(name: "My Videos")

        try sut.save(folder)

        let fetched = try sut.fetch(id: folder.id)
        XCTAssertNotNil(fetched)
        XCTAssertEqual(fetched?.name, "My Videos")
    }

    func testSave_multipleFolders_allPersisted() throws {
        try sut.save(TestFixtures.makeFolder(name: "Folder 1"))
        try sut.save(TestFixtures.makeFolder(name: "Folder 2"))
        try sut.save(TestFixtures.makeFolder(name: "Folder 3"))

        let all = try sut.fetchAll()
        XCTAssertEqual(all.count, 3)
    }

    // MARK: - Update Tests

    func testUpdate_modifiesExistingFolder() throws {
        var folder = TestFixtures.makeFolder(name: "Original")
        try sut.save(folder)

        folder.name = "Updated"
        try sut.update(folder)

        let fetched = try sut.fetch(id: folder.id)
        XCTAssertEqual(fetched?.name, "Updated")
    }

    func testRename_changesName() throws {
        let folder = TestFixtures.makeFolder(name: "Old Name")
        try sut.save(folder)

        try sut.rename(folder, to: "New Name")

        let fetched = try sut.fetch(id: folder.id)
        XCTAssertEqual(fetched?.name, "New Name")
    }

    // MARK: - Delete Tests

    func testDelete_removesFolderFromDatabase() throws {
        let folder = TestFixtures.makeFolder()
        try sut.save(folder)

        try sut.delete(folder)

        let fetched = try sut.fetch(id: folder.id)
        XCTAssertNil(fetched)
    }

    func testDelete_setsVideosToNilFolder() throws {
        // Create folder and video in that folder
        let folder = TestFixtures.makeFolder()
        try sut.save(folder)

        // Insert a video directly into the database with this folder ID
        try dbPool.write { db in
            let video = TestFixtures.makeVideo(folderID: folder.id)
            try video.save(db)
        }

        // Delete the folder
        try sut.delete(folder)

        // Verify the video's folderID is now nil
        let video = try dbPool.read { db in
            try Video.fetchOne(db)
        }
        XCTAssertNil(video?.folderID)
    }

    // MARK: - Fetch Tests

    func testFetchAll_returnsAllFolders() throws {
        try sut.save(TestFixtures.makeFolder())
        try sut.save(TestFixtures.makeFolder())

        let all = try sut.fetchAll()

        XCTAssertEqual(all.count, 2)
    }

    func testFetchAll_orderedByNameAscending() throws {
        try sut.save(TestFixtures.makeFolder(name: "Zebra"))
        try sut.save(TestFixtures.makeFolder(name: "Apple"))
        try sut.save(TestFixtures.makeFolder(name: "Mango"))

        let all = try sut.fetchAll()

        XCTAssertEqual(all[0].name, "Apple")
        XCTAssertEqual(all[1].name, "Mango")
        XCTAssertEqual(all[2].name, "Zebra")
    }

    func testFetch_withInvalidID_returnsNil() throws {
        let result = try sut.fetch(id: UUID())
        XCTAssertNil(result)
    }

    // MARK: - Auto-Generated Folder Tests

    func testFetchAutoGeneratedFolders_returnsOnlyAutoGenerated() throws {
        try sut.save(TestFixtures.makeFolder(name: "Auto", isAutoGenerated: true))
        try sut.save(TestFixtures.makeFolder(name: "User", isAutoGenerated: false))

        let autoFolders = try sut.fetchAutoGeneratedFolders()

        XCTAssertEqual(autoFolders.count, 1)
        XCTAssertEqual(autoFolders.first?.name, "Auto")
    }

    func testFetchUserFolders_returnsOnlyUserCreated() throws {
        try sut.save(TestFixtures.makeFolder(name: "Auto", isAutoGenerated: true))
        try sut.save(TestFixtures.makeFolder(name: "User", isAutoGenerated: false))

        let userFolders = try sut.fetchUserFolders()

        XCTAssertEqual(userFolders.count, 1)
        XCTAssertEqual(userFolders.first?.name, "User")
    }

    func testFetchOrCreateAutoFolder_createsNewFolder() throws {
        let folder = try sut.fetchOrCreateAutoFolder(for: "youtube.com")

        XCTAssertEqual(folder.name, "youtube.com")
        XCTAssertTrue(folder.isAutoGenerated)

        // Verify it's actually in the database
        let fetched = try sut.fetch(id: folder.id)
        XCTAssertNotNil(fetched)
    }

    func testFetchOrCreateAutoFolder_returnsExistingFolder() throws {
        // Create the folder first
        let original = try sut.fetchOrCreateAutoFolder(for: "youtube.com")

        // Call again with same domain
        let fetched = try sut.fetchOrCreateAutoFolder(for: "youtube.com")

        XCTAssertEqual(original.id, fetched.id)
    }

    func testFetchOrCreateAutoFolder_differentDomains_createsDifferentFolders() throws {
        let youtube = try sut.fetchOrCreateAutoFolder(for: "youtube.com")
        let vimeo = try sut.fetchOrCreateAutoFolder(for: "vimeo.com")

        XCTAssertNotEqual(youtube.id, vimeo.id)
        XCTAssertEqual(youtube.name, "youtube.com")
        XCTAssertEqual(vimeo.name, "vimeo.com")
    }

    // MARK: - Video Count Tests

    func testVideoCount_returnsCorrectCount() throws {
        let folder = TestFixtures.makeFolder()
        try sut.save(folder)

        // Insert videos directly into database
        try dbPool.write { db in
            try TestFixtures.makeVideo(folderID: folder.id).save(db)
            try TestFixtures.makeVideo(folderID: folder.id).save(db)
            try TestFixtures.makeVideo(folderID: folder.id).save(db)
        }

        let count = try sut.videoCount(in: folder)

        XCTAssertEqual(count, 3)
    }

    func testVideoCount_emptyFolder_returnsZero() throws {
        let folder = TestFixtures.makeFolder()
        try sut.save(folder)

        let count = try sut.videoCount(in: folder)

        XCTAssertEqual(count, 0)
    }

    func testVideoCount_countsOnlyVideosInSpecificFolder() throws {
        let folder1 = TestFixtures.makeFolder(name: "Folder 1")
        let folder2 = TestFixtures.makeFolder(name: "Folder 2")
        try sut.save(folder1)
        try sut.save(folder2)

        try dbPool.write { db in
            try TestFixtures.makeVideo(folderID: folder1.id).save(db)
            try TestFixtures.makeVideo(folderID: folder1.id).save(db)
            try TestFixtures.makeVideo(folderID: folder2.id).save(db)
        }

        let count1 = try sut.videoCount(in: folder1)
        let count2 = try sut.videoCount(in: folder2)

        XCTAssertEqual(count1, 2)
        XCTAssertEqual(count2, 1)
    }

    // MARK: - Auto Folder Factory Tests

    func testAutoFolder_createsWithCorrectProperties() {
        let folder = Folder.autoFolder(for: "example.com")

        XCTAssertEqual(folder.name, "example.com")
        XCTAssertTrue(folder.isAutoGenerated)
    }
}
