import XCTest
@testable import OfflineBrowser

final class FolderFactoryTests: XCTestCase {

    // MARK: - autoFolder(for:) Tests

    func testAutoFolder_setsNameToDomain() {
        let folder = Folder.autoFolder(for: "example.com")
        XCTAssertEqual(folder.name, "example.com")
    }

    func testAutoFolder_setsIsAutoGeneratedToTrue() {
        let folder = Folder.autoFolder(for: "example.com")
        XCTAssertTrue(folder.isAutoGenerated)
    }

    func testAutoFolder_generatesUniqueID() {
        let folder1 = Folder.autoFolder(for: "example.com")
        let folder2 = Folder.autoFolder(for: "example.com")

        XCTAssertNotEqual(folder1.id, folder2.id)
    }

    func testAutoFolder_setsCreatedAtToNow() {
        let before = Date()
        let folder = Folder.autoFolder(for: "example.com")
        let after = Date()

        XCTAssertGreaterThanOrEqual(folder.createdAt, before)
        XCTAssertLessThanOrEqual(folder.createdAt, after)
    }

    func testAutoFolder_withSubdomain() {
        let folder = Folder.autoFolder(for: "www.example.com")
        XCTAssertEqual(folder.name, "www.example.com")
    }

    func testAutoFolder_withLongDomain() {
        let domain = "very-long-subdomain.another-subdomain.example.co.uk"
        let folder = Folder.autoFolder(for: domain)
        XCTAssertEqual(folder.name, domain)
    }

    func testAutoFolder_withEmptyString() {
        let folder = Folder.autoFolder(for: "")
        XCTAssertEqual(folder.name, "")
        XCTAssertTrue(folder.isAutoGenerated)
    }

    func testAutoFolder_withSpecialCharacters() {
        let domain = "test-site_123.example.com"
        let folder = Folder.autoFolder(for: domain)
        XCTAssertEqual(folder.name, domain)
    }

    // MARK: - Manual Folder Creation Tests

    func testManualFolder_defaultIsAutoGenerated_isFalse() {
        let folder = Folder(name: "My Videos")
        XCTAssertFalse(folder.isAutoGenerated)
    }

    func testManualFolder_canSetIsAutoGeneratedExplicitly() {
        let folder = Folder(name: "My Videos", isAutoGenerated: true)
        XCTAssertTrue(folder.isAutoGenerated)
    }

    func testManualFolder_generatesID() {
        let folder = Folder(name: "My Videos")
        XCTAssertNotNil(folder.id)
    }

    func testManualFolder_canUseCustomID() {
        let customID = UUID()
        let folder = Folder(id: customID, name: "My Videos")
        XCTAssertEqual(folder.id, customID)
    }

    func testManualFolder_canUseCustomCreatedAt() {
        let customDate = Date(timeIntervalSince1970: 0)
        let folder = Folder(name: "My Videos", createdAt: customDate)
        XCTAssertEqual(folder.createdAt, customDate)
    }
}
