import Foundation
import GRDB
import Combine

final class FolderRepository {
    static let shared = FolderRepository()

    // MARK: - Dependencies

    private let dbPool: DatabasePool

    // MARK: - Initialization

    init(dbPool: DatabasePool = DatabaseManager.shared.databasePool) {
        self.dbPool = dbPool
    }

    // MARK: - CRUD Operations

    func save(_ folder: Folder) throws {
        try dbPool.write { db in
            try folder.save(db)
        }
    }

    func update(_ folder: Folder) throws {
        try dbPool.write { db in
            try folder.update(db)
        }
    }

    func delete(_ folder: Folder) throws {
        try dbPool.write { db in
            // Move videos from this folder to root (nil folder)
            try db.execute(
                sql: "UPDATE videos SET folderID = NULL WHERE folderID = ?",
                arguments: [folder.id]
            )
            _ = try folder.delete(db)
        }
    }

    // MARK: - Queries

    func fetchAll() throws -> [Folder] {
        try dbPool.read { db in
            try Folder
                .order(Folder.Columns.name.asc)
                .fetchAll(db)
        }
    }

    func fetch(id: UUID) throws -> Folder? {
        try dbPool.read { db in
            try Folder.fetchOne(db, key: id)
        }
    }

    func fetchAutoGeneratedFolders() throws -> [Folder] {
        try dbPool.read { db in
            try Folder
                .filter(Folder.Columns.isAutoGenerated == true)
                .order(Folder.Columns.name.asc)
                .fetchAll(db)
        }
    }

    func fetchUserFolders() throws -> [Folder] {
        try dbPool.read { db in
            try Folder
                .filter(Folder.Columns.isAutoGenerated == false)
                .order(Folder.Columns.name.asc)
                .fetchAll(db)
        }
    }

    func fetchOrCreateAutoFolder(for domain: String) throws -> Folder {
        try dbPool.write { db in
            if let existing = try Folder
                .filter(Folder.Columns.name == domain)
                .filter(Folder.Columns.isAutoGenerated == true)
                .fetchOne(db) {
                return existing
            }

            let folder = Folder.autoFolder(for: domain)
            try folder.insert(db)
            return folder
        }
    }

    func rename(_ folder: Folder, to newName: String) throws {
        var updated = folder
        updated.name = newName
        try dbPool.write { db in
            try updated.update(db)
        }
    }

    // MARK: - Statistics

    func videoCount(in folder: Folder) throws -> Int {
        try dbPool.read { db in
            try Video
                .filter(Video.Columns.folderID == folder.id)
                .fetchCount(db)
        }
    }

    // MARK: - Observation

    func observeAll() -> AnyPublisher<[Folder], Error> {
        ValueObservation
            .tracking { db in
                try Folder
                    .order(Folder.Columns.name.asc)
                    .fetchAll(db)
            }
            .publisher(in: dbPool, scheduling: .immediate)
            .eraseToAnyPublisher()
    }
}
