import Foundation
import Combine

// MARK: - Video Repository Protocol

protocol VideoRepositoryProtocol {
    // CRUD
    func save(_ video: Video) throws
    func update(_ video: Video) throws
    func delete(_ video: Video) throws
    func deleteAll() throws

    // Queries
    func fetchAll() throws -> [Video]
    func fetch(id: UUID) throws -> Video?
    func fetchVideos(inFolder folderID: UUID?) throws -> [Video]
    func search(query: String) throws -> [Video]
    func fetchRecent(limit: Int) throws -> [Video]
    func fetchByDomain(_ domain: String) throws -> [Video]

    // Playback
    func updatePlaybackPosition(videoID: UUID, position: Int) throws

    // Statistics
    func totalStorageUsed() throws -> Int64
    func videoCount() throws -> Int

    // Observation
    func observeAll() -> AnyPublisher<[Video], Error>
    func observeVideos(inFolder folderID: UUID?) -> AnyPublisher<[Video], Error>
}

// MARK: - Default Parameter Values for VideoRepositoryProtocol

extension VideoRepositoryProtocol {
    func fetchRecent() throws -> [Video] {
        try fetchRecent(limit: 20)
    }
}

// MARK: - Download Repository Protocol

protocol DownloadRepositoryProtocol {
    // CRUD
    func save(_ download: Download) throws
    func update(_ download: Download) throws
    func delete(_ download: Download) throws
    func deleteCompleted() throws

    // Queries
    func fetchAll() throws -> [Download]
    func fetch(id: UUID) throws -> Download?
    func fetchPending() throws -> [Download]
    func fetchActive() throws -> [Download]
    func fetchFailed() throws -> [Download]
    func fetchNextPending() throws -> Download?

    // Status Updates
    func updateStatus(_ download: Download, to status: DownloadStatus) throws
    func updateProgress(_ download: Download, progress: Double, segmentsDownloaded: Int) throws
    func markFailed(_ download: Download, error: String) throws
    func resetForRetry(_ download: Download) throws

    // Observation
    func observeAll() -> AnyPublisher<[Download], Error>
    func observeActive() -> AnyPublisher<[Download], Error>
}

// MARK: - Folder Repository Protocol

protocol FolderRepositoryProtocol {
    // CRUD
    func save(_ folder: Folder) throws
    func update(_ folder: Folder) throws
    func delete(_ folder: Folder) throws

    // Queries
    func fetchAll() throws -> [Folder]
    func fetch(id: UUID) throws -> Folder?
    func fetchAutoGeneratedFolders() throws -> [Folder]
    func fetchUserFolders() throws -> [Folder]
    func fetchOrCreateAutoFolder(for domain: String) throws -> Folder
    func rename(_ folder: Folder, to newName: String) throws

    // Statistics
    func videoCount(in folder: Folder) throws -> Int

    // Observation
    func observeAll() -> AnyPublisher<[Folder], Error>
}

// MARK: - Repository Conformances

extension VideoRepository: VideoRepositoryProtocol {}
extension DownloadRepository: DownloadRepositoryProtocol {}
extension FolderRepository: FolderRepositoryProtocol {}
